version: "3.8"

services:
  app:
    image: dibkb/neo-tube-server:production
    ports:
      - "8000:8000"
    environment:
      - .env
    depends_on:
      - redis
      - prometheus
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
