version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.mac
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app # Mount app source code for hot reload
    ports:
      - "8000:8000"
    environment:
      - .env
    depends_on:
      - redis
      - prometheus
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
